/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 devsocMoniFinal1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/devsocMoniFinal1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials['body.006']} position={[-0.535, 38.721, 6.605]} scale={99.426} />
      <mesh geometry={nodes.Screen001.geometry} material={materials['body.006']} position={[-0.231, 49.952, -30.591]} scale={99.426} />
      <mesh geometry={nodes.MainButtonHolder001.geometry} material={materials['body.006']} position={[-23.733, 19.893, -28.432]} scale={[-4.764, -2.125, -7.321]} />
      <mesh geometry={nodes.MainButton001.geometry} material={materials['redButton.005']} position={[-23.888, 19.959, -29.487]} scale={[-2.598, -1.088, -7.108]} />
      <mesh geometry={nodes.BottomFront001.geometry} material={materials['body.006']} position={[11.664, 9.035, -24.31]} scale={[11.866, 3.503, 1.131]}>
        <mesh geometry={nodes.Correctbottom001.geometry} material={materials['body.006']} position={[-1.009, -0.552, 27.369]} scale={[2.521, 1.572, 26.29]} />
      </mesh>
      <mesh geometry={nodes.HACKTIME4001.geometry} material={materials['Asset 1.005']} position={[-2.301, 50.215, -37.143]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[46.932, 44.607, 44.607]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.007']} position={[0.1, 50.442, -36.64]} rotation={[Math.PI / 2, 0, 0]} scale={[21.85, 28.176, 21.732]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.008']} position={[2.864, 8.395, -24.187]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.72, -0.304, -0.52]} />
    </group>
  )
}

useGLTF.preload('/devsocMoniFinal1.gltf')
